import {SubmissionForm} from './validation';
import {useState} from 'react';
import {CalendarDays,Clock,LogOut,Mail,ShieldCheck,UserRound} from 'lucide-react';
import {modules,date} from './config';
type AdminUser={id?:number|string;name:string;email?:string;role:string;status?:string;created_at?:string;version?:number;updated_at?:string};
export default function AdminProfile({user,permissions,onSignOut,onSave}:{user:AdminUser;permissions:string[];onSignOut:()=>Promise<void>;onSave:(details:{name:string;email:string;version?:number})=>Promise<void>}){
 const [busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');const initials=user.name.trim().split(/\s+/).map(part=>part[0]).slice(0,2).join('').toUpperCase();
 const access=modules.filter(module=>user.role==='Admin'||permissions.includes(module.key)).map(module=>module.label);for(const [key,label] of [['reports','Reports & analytics'],['settings','Store settings']])if(user.role==='Admin'||permissions.includes(key))access.push(label);if(user.role==='Admin')access.push('Activity log');
 const details=[{label:'Full name',value:user.name,Icon:UserRound},{label:'Email address',value:user.email||'Not provided',Icon:Mail},{label:'Role',value:user.role,Icon:ShieldCheck},{label:'Account status',value:user.status||'Active',Icon:ShieldCheck},{label:'Account created',value:date(user.created_at||''),Icon:CalendarDays},{label:'Last account update',value:date(user.updated_at||''),Icon:Clock}];
 return <><div className="page-heading"><div><div className="eyebrow olive">YOUR WORKSPACE ACCOUNT</div><h1>Admin profile<span className="heading-dot">.</span></h1><p>Your personal details and access to LEEKAV Commerce.</p></div></div><div className="admin-profile-layout"><aside className="panel admin-profile-summary"><span className="admin-profile-avatar">{initials}</span><h2>{user.name}</h2><p>{user.email}</p><span className="admin-profile-role"><ShieldCheck size={15}/>{user.role}</span><div className="admin-profile-status"><span className={'badge '+(user.status==='Active'?'green':'gray')}><span/>{user.status||'Active'}</span></div><div className="admin-profile-signout"><button className="button secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await onSignOut();}finally{setBusy(false);}}}><LogOut size={16}/>{busy?'Signing out…':'Sign out'}</button></div></aside><div className="admin-profile-content"><section className="panel"><div className="panel-heading"><div><h2>Profile details</h2><p>Information associated with your staff account.</p></div>{!editing&&<button className="button secondary" onClick={()=>{setError('');setEditing(true);}}>Edit details</button>}</div>{editing&&<SubmissionForm className="admin-profile-edit" onSubmit={async event=>{const input=new FormData(event.currentTarget);setSaving(true);setError('');try{await onSave({name:String(input.get('name')||'').trim(),email:String(input.get('email')||'').trim(),version:user.version});setEditing(false);}catch(error:any){setError(error.message);}finally{setSaving(false);}}}><label>Full name<input name="name" defaultValue={user.name} required maxLength={180} autoComplete="name" disabled={saving}/></label><label>Email address<input name="email" type="email" defaultValue={user.email} required maxLength={254} autoComplete="email" disabled={saving}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="admin-profile-edit-actions"><button className="button" disabled={saving}>{saving?'Saving…':'Save changes'}</button><button type="button" className="button secondary" disabled={saving} onClick={()=>setEditing(false)}>Cancel</button></div></SubmissionForm>}<dl className="admin-profile-details">{details.map(({label,value,Icon})=><div key={label}><dt><Icon size={16}/>{label}</dt><dd>{value}</dd></div>)}</dl></section><section className="panel"><div className="panel-heading"><div><h2>Role & access</h2><p>{user.role==='Admin'?'Your administrator role provides access to all workspace modules.':'Your assigned role determines which workspace modules you can access.'}</p></div></div><div className="admin-profile-access">{access.map(label=><span key={label}><ShieldCheck size={14}/>{label}</span>)}{!access.length&&<p>No module permissions are assigned to this account.</p>}</div><p className="admin-profile-help">Staff roles and permissions are managed through Admin Users & Roles.</p></section></div></div></>;
}
