export type Row = { id: string; version: number; created_at?: string; updated_at?: string; [key: string]: any };
export type Field = { key: string; label: string; type?: string; required?: boolean; options?: string[]; resource?: string; placeholder?: string; hint?: string; wide?: boolean };
export type Module = { key: string; label: string; singular: string; description: string; group: string; fields: Field[]; columns: string[] };
const name: Field = { key: 'name', label: 'Name', required: true };
const description: Field = { key: 'description', label: 'Description', type: 'textarea', wide: true };
const status: Field = { key: 'status', label: 'Status', type: 'select', options: ['Active','Inactive'] };
const ref = (key:string,label:string,resource:string,required=false):Field => ({key,label,type:'reference',resource,required});
const n = (key:string,label:string,required=false):Field => ({key,label,type:'number',required});
export const modules: Module[] = [
 {key:'products',label:'Products',singular:'product',description:'Every product, every detail. Your catalog in one place.',group:'Catalog',columns:['name','sku','brand_id','price','stock','status'],fields:[name,{key:'sku',label:'SKU / stock code',required:true},{key:'type',label:'Product type',type:'select',options:['Simple','Variable']},ref('brand_id','Brand','brands'),ref('category_ids','Categories','categories'),{key:'status',label:'Publication status',type:'select',options:['Draft','Active','Inactive']},n('price','Regular price (KES)',true),n('sale_price','Sale price (KES)'),n('stock','Opening stock'),n('low_stock_threshold','Low-stock threshold'),{key:'image',label:'Product image',type:'image',wide:true},description,{key:'specifications',label:'Specifications',type:'textarea',hint:'One specification per line: Capacity: 8 kg',wide:true},{key:'warranty',label:'Warranty information',wide:true},{key:'manual',label:'Manual / brochure PDF',type:'file',wide:true},{key:'seo_title',label:'SEO title',wide:true},{key:'seo_description',label:'SEO description',type:'textarea',wide:true},{key:'slug',label:'Product URL slug',required:true,hint:'Unique across all products, including retired products.',placeholder:'midea-front-load-washer'}]},
 {key:'brands',label:'Brands',singular:'brand',description:'Build a distinct home for every brand you carry.',group:'Catalog',columns:['name','description','status'],fields:[name,status,{key:'image',label:'Brand logo',type:'image'},{key:'banner',label:'Brand banner',type:'image'},description,{key:'website',label:'Website',type:'url'}]},
 {key:'categories',label:'Categories',singular:'category',description:'Organize your catalog into a clear, browsable hierarchy.',group:'Catalog',columns:['name','parent_id','slug','status'],fields:[name,ref('parent_id','Parent category','categories'),status,{key:'slug',label:'Public URL slug',required:true},description,{key:'image',label:'Category image',type:'image'}]},
 {key:'attributes',label:'Attributes & specifications',singular:'attribute',description:'Reusable product details for filters and specification tables.',group:'Catalog',columns:['name','code','input_type','unit','filterable'],fields:[name,{key:'code',label:'Permanent code',required:true},{key:'input_type',label:'Input type',type:'select',options:['Text','Number','Single choice','Multiple choice','Yes/No']},{key:'unit',label:'Unit',placeholder:'kg, W, cm'}, {key:'options',label:'Choice options',type:'textarea',hint:'One option per line',wide:true},{key:'filterable',label:'Use as storefront filter',type:'checkbox'},{key:'required',label:'Required on products',type:'checkbox'}]},
 {key:'inventory',label:'Stock / inventory',singular:'stock adjustment',description:'Keep availability accurate and catch low stock early.',group:'Catalog',columns:['name','sku','stock','reserved','available','low_stock_threshold'],fields:[ref('product_id','Product','products',true),n('quantity','Adjustment quantity (+ / -)',true),{key:'reason',label:'Reason for adjustment',required:true,wide:true}]},
 {key:'customers',label:'Customers',singular:'customer',description:'A closer view of the people behind your orders.',group:'Commerce',columns:['name','email','phone','account_type','status'],fields:[name,{key:'email',label:'Email address',type:'email',required:true},{key:'phone',label:'Phone number'},{key:'account_type',label:'Account type',type:'select',options:['Individual','Business']},{key:'company',label:'Company'},status,{key:'address',label:'Delivery address',type:'textarea',wide:true},{key:'county',label:'County / town'},{key:'marketing_consent',label:'Consents to marketing emails',type:'checkbox'},{key:'notes',label:'Internal notes',type:'textarea',wide:true}]},
 {key:'delivery-zones',label:'Delivery zones & rates',singular:'delivery zone',description:'Set delivery charges and free-delivery rules by location.',group:'Configuration',columns:['name','towns','charge','free_threshold','status'],fields:[name,{key:'towns',label:'Counties / towns',type:'textarea',required:true,hint:'One county or town per line',wide:true},n('charge','Delivery charge (KES)',true),n('free_threshold','Free-delivery threshold (KES)'),status]},
 {key:'taxes',label:'Tax settings',singular:'tax rule',description:'Manage VAT rates and the way your prices include tax.',group:'Configuration',columns:['name','rate','inclusive','status'],fields:[name,n('rate','VAT rate (%)',true),{key:'inclusive',label:'Product prices include VAT',type:'checkbox'},status]},
 {key:'coupons',label:'Coupons & discounts',singular:'coupon',description:'Create offers that give customers a reason to return.',group:'Content & marketing',columns:['name','code','discount_kind','discount_type','value','usage','status'],fields:[name,{key:'code',label:'Coupon code',required:true},{key:'discount_type',label:'Discount type',type:'select',options:['Percentage','Fixed']},n('value','Discount value',true),n('min_order','Minimum order value (KES)'),n('usage_limit','Usage limit'),{key:'starts_at',label:'Valid from',type:'date'},{key:'ends_at',label:'Valid until',type:'date'},status]},
 {key:'banners',label:'Homepage content',singular:'banner',description:'Keep your storefront fresh with campaigns and featured collections.',group:'Content & marketing',columns:['name','placement','link','status'],fields:[name,{key:'placement',label:'Placement',type:'select',options:['Hero slider','Promotional banner','Featured brand','Featured product']},{key:'image',label:'Banner image',type:'image',wide:true},{key:'headline',label:'Headline'},{key:'link',label:'Destination URL'},description,status]},
 {key:'pages',label:'CMS pages',singular:'page',description:'Publish helpful information with clean URLs and SEO details.',group:'Content & marketing',columns:['name','slug','updated_at','status'],fields:[name,{key:'slug',label:'URL slug',required:true},{key:'body',label:'Page content',type:'textarea',wide:true,required:true},{key:'seo_title',label:'SEO title'},{key:'seo_description',label:'SEO description',type:'textarea',wide:true},status]},
 {key:'users',label:'Admin users & roles',singular:'admin user',description:'Give your team the access they need, with accountability.',group:'Configuration',columns:['name','email','role','status'],fields:[name,{key:'email',label:'Email address',type:'email',required:true},{key:'password',label:'Password',type:'password',hint:'At least 12 characters. Leave blank when editing to keep the password.'},{key:'role',label:'Role',type:'select',options:['Admin','Sales','Store Manager']},status]},
 {key:'orders',label:'Orders',singular:'order',description:'From confirmation to delivery. Follow every order.',group:'Commerce',columns:['reference','customer_name','total','payment_status','status','created_at'],fields:[]},
 {key:'payment-methods',label:'Payment methods',singular:'payment method',description:'Configure online gateways and manual payment options.',group:'Configuration',columns:['name','category','provider','environment','status'],fields:[]},
 {key:'payments',label:'Payment history / transactions',singular:'transaction',description:'Customer checkout payments, references and refund history.',group:'Commerce',columns:['payment_id','order_reference','customer_name','method','amount','status','reference','created_at'],fields:[{key:'notes',label:'Internal notes',type:'textarea',wide:true}]},
 {key:'returns',label:'Returns & refunds',singular:'return request',description:'Handle requests with a clear reason, decision and history.',group:'Commerce',columns:['reference','order_reference','reason','refund_amount','refund_status','status'],fields:[ref('order_id','Order','orders',true),{key:'reason',label:'Reason for return',type:'textarea',required:true,wide:true},n('refund_amount','Requested refund (KES)',true),{key:'status',label:'Request status',type:'select',options:['Requested','Approved','Received','Rejected']},{key:'notes',label:'Inspection notes',type:'textarea',wide:true}]},
 {key:'enquiries',label:'Enquiries',singular:'enquiry',description:'Turn customer questions into helpful conversations.',group:'Commerce',columns:['name','email','subject','status','created_at'],fields:[name,{key:'email',label:'Email address',type:'email',required:true},{key:'subject',label:'Subject',required:true},ref('product_id','Related product','products'),{key:'message',label:'Message',type:'textarea',required:true,wide:true},{key:'status',label:'Status',type:'select',options:['Open','In progress','Resolved']},{key:'notes',label:'Response notes',type:'textarea',wide:true}]},
 {key:'emails',label:'Email notifications',singular:'email template',description:'Make every customer update clear and consistent.',group:'Content & marketing',columns:['name','event','subject','status'],fields:[name,{key:'event',label:'Event',type:'select',options:['Order confirmation','Order status update','Admin new order','Payment successful','Password reset']},{key:'subject',label:'Email subject',required:true,wide:true},{key:'body',label:'Email body',type:'textarea',required:true,wide:true,hint:'Use {{customer_name}}, {{order_reference}} and {{total}}.'},status]},
];
export const settingsFields: Field[] = [
 {key:'store_name',label:'Store name',required:true},{key:'email',label:'Contact email',type:'email'},{key:'phone',label:'Contact phone'}, {key:'whatsapp',label:'WhatsApp number'},
 {key:'address',label:'Store address',type:'textarea',wide:true},{key:'logo',label:'Store logo',type:'image'}, {key:'facebook',label:'Facebook URL',type:'url'},{key:'instagram',label:'Instagram URL',type:'url'},
 {key:'mail_transport',label:'Email transport',type:'select',options:['Log (local preview)','SMTP','Amazon SES']},{key:'smtp_host',label:'SMTP host'},{key:'smtp_port',label:'SMTP port',type:'number'},{key:'smtp_username',label:'SMTP username'},{key:'smtp_password',label:'SMTP password',type:'password'},{key:'mail_from',label:'Sender email',type:'email'},
 {key:'cdn_url',label:'CDN asset URL',type:'url',placeholder:'https://cdn.yourstore.com'},
 {key:'ga4_id',label:'Google Analytics 4 measurement ID',placeholder:'G-XXXXXXXXXX'},{key:'meta_pixel_id',label:'Meta Pixel ID'},
];
export const titles: Record<string,string> = Object.fromEntries(modules.map(m=>[m.key,m.label]));
export const money = (value:any) => `KES ${Number(value??0).toLocaleString('en-KE',{minimumFractionDigits:0,maximumFractionDigits:2})}`;
export const date = (value:string) => value ? new Date(value).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}) : '—';
