export type Row = { id: string; version: number; created_at?: string; updated_at?: string; [key: string]: any };
export type Field = { key: string; label: string; type?: string; required?: boolean; options?: string[]; resource?: string; placeholder?: string; hint?: string; wide?: boolean };
export type Module = { key: string; label: string; singular: string; description: string; group: string; fields: Field[]; columns: string[] };
const name: Field = { key: 'name', label: 'Name', required: true };
const description: Field = { key: 'description', label: 'Description', type: 'textarea', wide: true };
const status: Field = { key: 'status', label: 'Status', type: 'select', options: ['Active','Inactive'] };
const ref = (key:string,label:string,resource:string,required=false):Field => ({key,label,type:'reference',resource,required});
const n = (key:string,label:string,required=false):Field => ({key,label,type:'number',required});
export const modules: Module[] = [
 {key:'products',label:'Products',singular:'product',description:'Every product, every detail. Your catalog in one place.',group:'Catalog',columns:['name','sku','brand_id','price','stock','status'],fields:[name,{key:'sku',label:'SKU / stock code',required:true},{key:'type',label:'Product type',type:'select',options:['Simple','Variable']},ref('brand_id','Brand','brands'),ref('category_ids','Categories','categories'),{key:'status',label:'Publication status',type:'select',options:['Active','Inactive']},n('price','Regular price (KES)',true),n('sale_price','Sale price (KES)'),n('stock','Opening stock'),n('low_stock_threshold','Low-stock threshold'),{key:'featured',label:'Show in featured products',type:'checkbox'},{key:'deal',label:'Include in Deals (homepage and Deals page)',type:'checkbox'},{key:'new_arrival',label:'Show in new arrivals',type:'checkbox'},{key:'image',label:'Main Image',type:'image',wide:true,hint:'Primary product image. Upload one image.'},{key:'gallery_images',label:'Gallery Images',type:'gallery',wide:true,hint:'Upload multiple product images. JPG, PNG or WebP, up to 5 MB each.'},description,{key:'specifications',label:'Specifications',type:'textarea',hint:'One specification per line: Capacity: 8 kg',wide:true},{key:'warranty',label:'Warranty information',wide:true},{key:'manual',label:'Manual / brochure PDF',type:'file',wide:true},{key:'seo_title',label:'SEO title',wide:true},{key:'seo_description',label:'SEO description',type:'textarea',wide:true},{key:'slug',label:'Product URL slug',required:true,hint:'Unique across all products, including retired products.',placeholder:'midea-front-load-washer'}]},
 {key:'brands',label:'Brands',singular:'brand',description:'Build a distinct home for every brand you carry.',group:'Catalog',columns:['image','name','description','banner','website','status'],fields:[name,status,{key:'image',label:'Brand logo',type:'image'},{key:'banner',label:'Brand banner',type:'image'},description,{key:'website',label:'Website',type:'url'}]},
 {key:'categories',label:'Categories',singular:'category',description:'Organize the storefront navigation and category hierarchy.',group:'Catalog',columns:['name','parent_id','slug','status'],fields:[name,ref('parent_id','Parent category','categories'),status,{key:'slug',label:'Public URL slug',required:true},{key:'nav_label',label:'Navigation label'},n('sort_order','Display order'),description,{key:'image',label:'Category image',type:'image'},{key:'promo_image',label:'Navigation promotion image',type:'image'},{key:'promo_label',label:'Promotion label'},{key:'promo_headline',label:'Promotion headline'},{key:'promo_description',label:'Promotion description',type:'textarea',wide:true}]},
 {key:'attributes',label:'Attributes',singular:'attribute',description:'Reusable product details for filters and specification tables.',group:'Catalog',columns:['name','code','input_type','unit','filterable'],fields:[name,{key:'code',label:'Permanent code',required:true},{key:'input_type',label:'Input type',type:'select',options:['Text','Number','Single choice','Multiple choice','Yes/No']},{key:'unit',label:'Unit',placeholder:'kg, W, cm'}, {key:'options',label:'Choice options',type:'textarea',hint:'One option per line',wide:true},{key:'filterable',label:'Use as storefront filter',type:'checkbox'},{key:'required',label:'Required on products',type:'checkbox'}]},
 {key:'inventory',label:'Stock / inventory',singular:'stock',description:'Keep availability accurate and catch low stock early.',group:'Catalog',columns:['name','sku','stock','reserved','available','low_stock_threshold'],fields:[ref('product_id','Product','products',true),{...n('stock','Add Stock',true),hint:'Enter the new total stock quantity.'}]},
 {key:'customers',label:'Customers',singular:'customer',description:'A closer view of the people behind your orders.',group:'Commerce',columns:['name','email','phone','account_type','status'],fields:[name,{key:'email',label:'Email address',type:'email',required:true},{key:'phone',label:'Phone number'},{key:'account_type',label:'Account type',type:'select',options:['Individual','Business']},{key:'company',label:'Company'},status,{key:'address',label:'Delivery address',type:'textarea',wide:true},{key:'county',label:'County / town'},{key:'marketing_consent',label:'Consents to marketing emails',type:'checkbox'},{key:'notes',label:'Internal notes',type:'textarea',wide:true}]},
 {key:'delivery-zones',label:'Delivery zones & rates',singular:'delivery zone',description:'Set delivery charges and free-delivery rules by location.',group:'Configuration',columns:['name','country_name','county_names','charge','free_threshold','status'],fields:[name,{key:'country_code',label:'Country',type:'country',required:true},{key:'county_codes',label:'Select Counties',type:'counties',required:true,wide:true},n('charge','Delivery charge (KES)',true),n('free_threshold','Free-delivery threshold (KES)'),status]},
 {key:'taxes',label:'Tax settings',singular:'tax rule',description:'Manage VAT rates and the way your prices include tax.',group:'Configuration',columns:['name','rate','inclusive','status'],fields:[name,n('rate','VAT rate (%)',true),{key:'inclusive',label:'Product prices include VAT',type:'checkbox'},status]},
 {key:'coupons',label:'Coupons & discounts',singular:'coupon',description:'Create checkout offers and publish active public codes to the storefront.',group:'Content & marketing',columns:['name','code','discount_kind','discount_type','value','usage','status'],fields:[name,{key:'code',label:'Coupon code',required:true},{key:'discount_kind',label:'Discount applies to',type:'select',options:['Order','Shipping']},{key:'discount_type',label:'Discount type',type:'select',options:['Percentage','Fixed','Free']},n('value','Discount value',true),{key:'eligibility',label:'Customer eligibility',type:'select',options:['All','Account type']},{key:'account_type',label:'Eligible account type',type:'select',options:['Individual','Business']},{key:'scope',label:'Product scope',type:'select',options:['All']},{key:'minimum_type',label:'Minimum requirement',type:'select',options:['None','Amount','Quantity']},n('minimum_amount','Minimum order value (KES)'),n('minimum_quantity','Minimum item quantity'),n('max_shipping','Maximum covered delivery charge'),n('usage_limit','Usage limit'),{key:'once_per_customer',label:'Limit to one use per customer',type:'checkbox'},{key:'starts_at',label:'Valid from',type:'date'},{key:'ends_at',label:'Valid until',type:'date'},description,status]},
 {key:'banners',label:'Homepage banners',singular:'banner',description:'Manage hero slides and campaign banners shown on the storefront.',group:'Content & marketing',columns:['name','placement','sort_order','status'],fields:[name,{key:'placement',label:'Placement',type:'select',options:['Hero slider','Promotional banner','Featured brand','Featured product']},{key:'eyebrow',label:'Eyebrow text'},{key:'image',label:'Banner image',type:'image',wide:true},{key:'headline',label:'Headline',required:true},{key:'cta_label',label:'Button label'},{key:'link',label:'Destination URL'},n('sort_order','Display order'),description,status]},
 {key:'homepage-sections',label:'Storefront sections',singular:'section',description:'Manage homepage and campaign-page headings, copy, images and calls to action.',group:'Content & marketing',columns:['name','key','sort_order','status'],fields:[name,{key:'key',label:'Section',type:'select',required:true,options:['categories','featured-products','deals','deals-page','editorial','new-arrivals','brands','journal']},{key:'eyebrow',label:'Eyebrow text'},{key:'heading',label:'Heading',required:true},{key:'body',label:'Supporting copy',type:'textarea',wide:true},{key:'image',label:'Section image',type:'image',wide:true},{key:'link_label',label:'Link label'},{key:'link',label:'Destination URL'},n('sort_order','Display order'),status]},
 {key:'articles',label:'Journal articles',singular:'article',description:'Publish buying guides, inspiration and appliance advice.',group:'Content & marketing',columns:['name','category','slug','status'],fields:[name,{key:'slug',label:'URL slug',required:true},{key:'category',label:'Article category',required:true},{key:'excerpt',label:'Summary',type:'textarea',wide:true,required:true},{key:'image',label:'Cover image',type:'image',wide:true,required:true},{key:'image_alt',label:'Image description',required:true},n('minutes','Reading time (minutes)',true),n('sort_order','Display order'),{key:'body',label:'Article content',type:'textarea',wide:true,required:true},status]},
 {key:'pages',label:'CMS pages',singular:'page',description:'Publish helpful information with clean URLs and SEO details.',group:'Content & marketing',columns:['name','slug','updated_at','status'],fields:[name,{key:'slug',label:'URL slug',required:true},{key:'body',label:'Page content',type:'textarea',wide:true,required:true},{key:'seo_title',label:'SEO title'},{key:'seo_description',label:'SEO description',type:'textarea',wide:true},status]},
 {key:'users',label:'Admin users & roles',singular:'admin user',description:'Give your team the access they need, with accountability.',group:'Configuration',columns:['name','email','role','status'],fields:[name,{key:'email',label:'Email address',type:'email',required:true},{key:'password',label:'Password',type:'password',hint:'At least 12 characters. Leave blank when editing to keep the password.'},{key:'role',label:'Role',type:'select',options:['Admin','Sales','Store Manager']},status]},
 {key:'orders',label:'Orders',singular:'order',description:'From confirmation to delivery. Follow every order.',group:'Commerce',columns:['reference','customer_name','total','payment_status','status','created_at'],fields:[]},
 {key:'payment-methods',label:'Payment methods',singular:'payment method',description:'Configure online gateways and manual payment options.',group:'Configuration',columns:['name','category','provider','environment','status'],fields:[]},
 {key:'payments',label:'Payment history / transactions',singular:'transaction',description:'Customer checkout payments, references and refund history.',group:'Commerce',columns:['payment_id','order_reference','customer_name','method','amount','status','reference','created_at'],fields:[{key:'notes',label:'Internal notes',type:'textarea',wide:true}]},
 {key:'returns',label:'Returns & refunds',singular:'return request',description:'Handle requests with a clear reason, decision and history.',group:'Commerce',columns:['reference','order_reference','reason','refund_amount','refund_status','status'],fields:[ref('order_id','Order','orders',true),{key:'reason',label:'Reason for return',type:'textarea',required:true,wide:true},n('refund_amount','Requested refund (KES)',true),{key:'status',label:'Request status',type:'select',options:['Requested','Approved','Received','Rejected']},{key:'notes',label:'Inspection notes',type:'textarea',wide:true}]},
 {key:'reviews',label:'Product Reviews',singular:'product review',description:'Review customer feedback and approve it for your storefront.',group:'Commerce',columns:['product_name','customer_name','rating','title','status','created_at'],fields:[]},
 {key:'enquiries',label:'Enquiries',singular:'enquiry',description:'Turn customer questions into helpful conversations.',group:'Commerce',columns:['name','email','subject','status','created_at'],fields:[name,{key:'email',label:'Email address',type:'email',required:true},{key:'subject',label:'Subject',required:true},ref('product_id','Related product','products'),{key:'message',label:'Message',type:'textarea',required:true,wide:true},{key:'status',label:'Status',type:'select',options:['Open','In progress','Resolved']},{key:'notes',label:'Response notes',type:'textarea',wide:true}]},
 {key:'emails',label:'Email notifications',singular:'email template',description:'Make every customer update clear and consistent.',group:'Content & marketing',columns:['name','event','subject','status'],fields:[name,{key:'event',label:'Event',type:'select',options:['Order confirmation','Order status update','Admin new order','Payment successful','Password reset']},{key:'subject',label:'Email subject',required:true,wide:true},{key:'body',label:'Email body',type:'textarea',required:true,wide:true,hint:'Use {{customer_name}}, {{order_reference}} and {{total}}.'},status]},
];
export const settingsFields: Field[] = [
 {key:'deals_tagline',label:'Homepage Deals tagline',placeholder:'Limited-time prices on the appliances your home needs.',hint:'Leave blank to use the default tagline.',wide:true},
 {key:'announcement',label:'Storefront announcement',placeholder:'Thoughtfully chosen. Delivered to your door.',wide:true},
 {key:'footer_tagline',label:'Footer tagline',placeholder:'Good brands. Thoughtful choices.',wide:true},
 {key:'site_title',label:'Storefront browser title',wide:true},{key:'site_description',label:'Storefront search description',type:'textarea',wide:true},
 {key:'store_name',label:'Store name',required:true},{key:'email',label:'Contact email',type:'email'},{key:'phone',label:'Contact phone'}, {key:'whatsapp',label:'WhatsApp number'},
 {key:'address',label:'Store address',type:'textarea',wide:true},{key:'logo',label:'Store logo',type:'image'},{key:'favicon',label:'Favicon',type:'image',hint:'Square PNG or WebP recommended. Used for the storefront browser tab icon.'}, {key:'facebook',label:'Facebook URL',type:'url'},{key:'instagram',label:'Instagram URL',type:'url'},
 {key:'mail_transport',label:'Email transport',type:'select',options:['Log (local preview)','SMTP','Amazon SES']},{key:'smtp_host',label:'SMTP host'},{key:'smtp_port',label:'SMTP port',type:'number'},{key:'smtp_username',label:'SMTP username'},{key:'smtp_password',label:'SMTP password',type:'password'},{key:'mail_from',label:'Sender email',type:'email'},
 {key:'cdn_url',label:'CDN asset URL',type:'url',placeholder:'https://cdn.yourstore.com'},
 {key:'ga4_id',label:'Google Analytics 4 measurement ID',placeholder:'G-XXXXXXXXXX'},{key:'meta_pixel_id',label:'Meta Pixel ID'},
];
export const titles: Record<string,string> = Object.fromEntries(modules.map(m=>[m.key,m.label]));
export const money = (value:any) => `KES ${Number(value??0).toLocaleString('en-KE',{minimumFractionDigits:0,maximumFractionDigits:2})}`;
export const date = (value:string) => value ? new Date(value).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}) : '—';
