import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Check,ChevronDown} from 'lucide-react';
type Props={value:string;options:string[];onChange:(value:string)=>void;label:string;disabled?:boolean};
export default function OrderStatusControl({value,options,onChange,label,disabled=false}:Props){
 const [open,setOpen]=useState(false),[position,setPosition]=useState({top:0,left:0});const trigger=useRef<HTMLButtonElement>(null),menu=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!open)return;const outside=(event:PointerEvent)=>{if(!trigger.current?.contains(event.target as Node)&&!menu.current?.contains(event.target as Node))setOpen(false);};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'){setOpen(false);trigger.current?.focus();}};const close=()=>setOpen(false);document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);window.addEventListener('resize',close);window.addEventListener('scroll',close,true);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape);window.removeEventListener('resize',close);window.removeEventListener('scroll',close,true);};},[open]);
 useEffect(()=>{if(disabled)setOpen(false);},[disabled]);
 return <><button ref={trigger} type="button" className={'order-status-trigger order-status-'+value.toLowerCase()} aria-label={label} aria-haspopup="menu" aria-expanded={open} title={value} disabled={disabled} onClick={()=>{const box=trigger.current!.getBoundingClientRect();setPosition({top:Math.min(box.bottom+6,window.innerHeight-245),left:Math.max(8,Math.min(box.left,window.innerWidth-218))});setOpen(!open);}}><i aria-hidden="true"/><span>{value}</span><ChevronDown size={13} aria-hidden="true"/></button>{open&&createPortal(<div ref={menu} className="order-status-menu" role="menu" aria-label="Choose order status" style={position}><span className="order-status-menu-heading">Order status</span>{['Pending','Confirmed','Dispatched','Delivered','Cancelled'].map(status=><button type="button" role="menuitemradio" aria-checked={value===status} disabled={!options.includes(status)} title={options.includes(status)?status:'Unavailable from '+value} className={value===status?'selected':''} key={status} onClick={()=>{setOpen(false);trigger.current?.focus();if(value!==status)onChange(status);}}><span>{status}</span>{value===status&&<Check size={14}/>}</button>)}</div>,document.body)}</>;
}
