import StatusControl from './status-control';
import {useEffect,useRef,useState} from 'react';
import {CheckCircle2,Loader2,MessageSquare,Package,Printer,SlidersHorizontal,Truck,Users,X} from 'lucide-react';
import {date,money} from './config';
import {TextEditor,RichContent} from './text-editor';
export default function OrderDetailsView({order,onClose,refresh,notify,canWrite,canPay,api,print,Overlay,Badge,StatusHistory,updateCache}:any){
 const [note,setNote]=useState(''),[busy,setBusy]=useState(false),[statusBusy,setStatusBusy]=useState(false),[error,setError]=useState('');
 return <Overlay onClose={onClose} wide className="order-detail-drawer"><div className="drawer-heading order-detail-heading"><div><span className="eyebrow olive">ORDER DETAILS</span><h2>{order.reference}</h2><p>{date(order.created_at)} · {order.source??'Customer order'}</p></div><div className="order-heading-actions"><button className="button secondary" onClick={print}><Printer size={16}/>Invoice</button><button className="icon-button" aria-label="Close order details" onClick={onClose}><X/></button></div></div><div className="drawer-body order-admin-body">
 <div className="order-overview"><div><span>Order status</span><Badge value={order.status}/></div><div><span>Payment status</span><Badge value={order.payment_status}/></div><div><span>Fulfilment</span><Badge value={order.fulfilment_status}/></div><div><span>Order total</span><strong>{money(order.total)}</strong></div></div>
 {canWrite&&<StatusEditor {...{order,refresh,notify,canPay,api,Badge,updateCache}} disabled={busy} onBusyChange={setStatusBusy}/>}
 <div className="order-information-grid"><section className="order-detail-card"><h3><Users size={17}/>Customer</h3><strong>{order.customer_name}</strong>{order.customer_email&&<a href={'mailto:'+order.customer_email}>{order.customer_email}</a>}{order.customer_phone&&<a href={'tel:'+order.customer_phone}>{order.customer_phone}</a>}</section><section className="order-detail-card"><h3><Truck size={17}/>Delivery</h3><p>{order.delivery_address}</p>{order.delivery_zone_name&&<small>{order.delivery_zone_name}</small>}</section></div>
 <div className="order-content-grid"><section className="order-detail-card order-products-card"><h3><Package size={17}/>Items <span className="count-pill">{order.lines?.length??0}</span></h3><div className="table-scroll"><table className="order-items"><thead><tr><th>Product</th><th>Qty</th><th>Total</th></tr></thead><tbody>{order.lines?.map((line:any)=><tr key={line.product_id}><td><strong>{line.name}</strong><small>SKU: {line.sku}</small></td><td>{line.quantity}</td><td>{money(line.total)}</td></tr>)}</tbody></table></div></section><section className="order-detail-card order-totals-card"><h3>Order summary</h3><div><span>Subtotal</span><strong>{money(order.subtotal)}</strong></div><div><span>Discount</span><strong>-{money(order.discount)}</strong></div><div><span>VAT {order.tax_inclusive?'(included)':''}</span><strong>{money(order.tax_total)}</strong></div><div><span>Delivery</span><strong>{money(order.shipping_total)}</strong></div><div className="order-grand-total"><span>Total</span><strong>{money(order.total)}</strong></div></section></div>
 <section className="order-detail-card"><h3><MessageSquare size={17}/>Internal notes</h3><RichContent value={order.notes||'No notes yet.'}/>{canWrite&&<div className="note-composer"><TextEditor name="order-note" label="Internal order note" maxLength={10000} value={note} onChange={setNote} disabled={busy||statusBusy} placeholder="Add a note for your team..."/>{error&&<div className="form-error" role="alert">{error}</div>}<button className="button secondary" disabled={!note.trim()||busy||statusBusy} onClick={async()=>{setBusy(true);setError('');try{const updated=await api(`order-actions/${order.id}`,'POST',{action:'note',evidence:note,version:order.version});updateCache(updated);await refresh();setNote('');notify('Note added.');}catch(error:any){setError(error.message);}finally{setBusy(false);}}}>{busy?'Saving...':'Add note'}</button></div>}</section>
 <details className="order-detail-card order-history-card"><summary>Status history <span>{(order.status_history?.length??0)+(order.payment_status_history?.length??0)} events</span></summary><div className="order-information-grid"><section><h4>Order history</h4><StatusHistory entries={order.status_history??[]}/></section><section><h4>Payment history</h4><StatusHistory entries={order.payment_status_history??[]}/></section></div></details>
 </div></Overlay>;
}
function StatusEditor({order,refresh,notify,canPay,disabled,api,Badge,updateCache,onBusyChange}:any){
 const [status,setStatus]=useState(order.status),[payment,setPayment]=useState(order.payment_status),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');const saving=useRef(false);
 useEffect(()=>{if(!saving.current){setStatus(order.status);setPayment(order.payment_status);}},[order.version,order.status,order.payment_status,busy]);
 const options:Record<string,string[]>={Pending:['Pending','Confirmed',...(order.payment_status!=='Paid'?['Cancelled']:[])],Confirmed:['Confirmed',...(order.payment_status==='Paid'?['Dispatched']:[]),...(order.payment_status!=='Paid'?['Cancelled']:[])],Dispatched:['Dispatched','Delivered'],Delivered:['Delivered'],Cancelled:['Cancelled']};
 const change=async(field:'status'|'payment_status',value:string)=>{if(saving.current||disabled||value===order[field])return;saving.current=true;setBusy(true);onBusyChange(true);setError('');setSaved('');field==='status'?setStatus(value):setPayment(value);const evidence=reason.trim()||`Admin changed ${field==='status'?'order':'payment'} status from ${order[field]} to ${value}.`;try{const updated=await api(canPay?`order-status/${order.id}`:`order-actions/${order.id}`,'POST',canPay?{version:order.version,[field]:value,evidence}:{version:order.version,action:({Confirmed:'confirm',Dispatched:'dispatch',Delivered:'deliver',Cancelled:'cancel'} as Record<string,string>)[value],evidence});updateCache(updated);setStatus(updated.status);setPayment(updated.payment_status);await refresh();setReason('');setSaved('Saved to order history');notify(`${field==='status'?'Order':'Payment'} status updated to ${value}.`);}catch(error:any){setStatus(order.status);setPayment(order.payment_status);setError(error.message);await refresh().catch(()=>{});}finally{saving.current=false;setBusy(false);onBusyChange(false);}};
 return <section className="order-detail-card order-status-card"><div className="order-card-heading"><div><h3><SlidersHorizontal size={18}/>Manage status</h3><p>Changes save immediately and are recorded in the history.</p></div><span className="order-save-feedback" role="status">{busy?<><Loader2 size={15} className="spin"/>Saving...</>:saved?<><CheckCircle2 size={15}/>{saved}</>:null}</span></div>{error&&<div className="form-error" role="alert">{error}</div>}<div className="order-status-fields"><label>Order status<StatusControl label="Order status" value={status} options={options[order.status]??[order.status]} disabled={busy||disabled} onChange={value=>void change('status',value)}/></label><label>Payment status{canPay?<StatusControl label="Payment status" value={payment} options={['Unpaid','Pending','Incomplete','Failed','Paid','Refunded','Partially refunded']} disabled={busy||disabled} onChange={value=>void change('payment_status',value)}/>:<div className="order-readonly-status"><Badge value={order.payment_status}/></div>}</label></div><details className="order-audit-note"><summary>Add an audit note (optional)</summary><label>Reason / reference<input aria-label="Status audit note" maxLength={10000} value={reason} disabled={busy||disabled} onChange={event=>setReason(event.target.value)} placeholder="Add context before changing a status"/></label></details><small>{canPay?'Payment status records collection or reconciliation; changing it does not charge or refund money.':'Payment status is managed by administrators.'}{order.status==='Confirmed'&&order.payment_status!=='Paid'?' Mark payment as Paid before dispatching.':''}</small></section>;
}
