import {useEffect,useRef,useState} from 'react';
import {EditorContent,useEditor} from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import CharacterCount from '@tiptap/extension-character-count';
import {Bold,Italic,Underline,List,ListOrdered,Quote,Link as LinkIcon,Unlink,Undo2,Redo2,RemoveFormatting} from 'lucide-react';
import {cleanRich,editorContent} from './rich-text';
export function TextEditor({value,onChange,name,label,required=false,maxLength=20000,plain=false,disabled=false,invalid=false,placeholder='Write here...'}:{value:string;onChange:(value:string)=>void;name:string;label:string;required?:boolean;maxLength?:number;plain?:boolean;disabled?:boolean;invalid?:boolean;placeholder?:string}){
 const wrapper=useRef<HTMLDivElement>(null),change=useRef(onChange);change.current=onChange;const [locked,setLocked]=useState(disabled),[linkOpen,setLinkOpen]=useState(false),[url,setUrl]=useState(''),[linkError,setLinkError]=useState('');
 const editor=useEditor({extensions:[StarterKit.configure(plain?{bold:false,italic:false,underline:false,strike:false,heading:false,bulletList:false,orderedList:false,listItem:false,listKeymap:false,blockquote:false,code:false,codeBlock:false,horizontalRule:false,link:false}:{heading:{levels:[2,3]},link:{openOnClick:false,autolink:false,protocols:['http','https','mailto']}}),CharacterCount.configure({})],content:editorContent(value,plain),immediatelyRender:false,shouldRerenderOnTransaction:true,editorProps:{attributes:{role:'textbox','aria-label':label,'aria-multiline':'true','data-placeholder':placeholder}},onUpdate:({editor})=>{const content=editor.isEmpty?'':plain?editor.getText({blockSeparator:'\n'}):cleanRich(editor.getHTML());change.current(content);wrapper.current?.dispatchEvent(new Event('input',{bubbles:true}));}},[plain,name]);
 useEffect(()=>{if(!editor)return;const current=editor.isEmpty?'':plain?editor.getText({blockSeparator:'\n'}):cleanRich(editor.getHTML());if(value!==current)editor.commands.setContent(editorContent(value,plain),{emitUpdate:false});},[value,editor,plain]);
 useEffect(()=>{const fieldset=wrapper.current?.closest('fieldset');const sync=()=>{const readonly=disabled||Boolean(fieldset?.disabled);setLocked(readonly);editor?.setEditable(!readonly);};sync();if(!fieldset)return;const observer=new MutationObserver(sync);observer.observe(fieldset,{attributes:true,attributeFilter:['disabled']});return()=>observer.disconnect();},[editor,disabled]);
 useEffect(()=>{editor?.view.dom.setAttribute('aria-invalid',String(invalid));},[editor,invalid]);
 const text=editor?.getText({blockSeparator:'\n'})||'';const serialized=editor?.isEmpty?'':plain?text:cleanRich(editor?.getHTML()||'');
 const tool=(title:string,Icon:any,run:()=>void,active=false,unavailable=false)=><button type="button" title={title} aria-label={title+' in '+label} aria-pressed={active} disabled={locked||!editor||unavailable} onMouseDown={event=>event.preventDefault()} onClick={run}><Icon size={16}/></button>;
 return <div ref={wrapper} className={'text-editor '+(plain?'plain-editor ':'')+(invalid?'invalid ':'')+(locked?'disabled':'')} data-editor={name} data-required={required} data-empty={!text.trim()} data-max-length={maxLength} data-value-length={serialized.length} data-disabled={locked}>
 <input type="hidden" name={name} value={value} disabled={locked}/>
 <div className="editor-toolbar" role="toolbar" aria-label={label+' formatting'}>{!plain&&<><select aria-label={'Text style in '+label} disabled={locked||!editor} value={editor?.isActive('heading',{level:2})?'h2':editor?.isActive('heading',{level:3})?'h3':'p'} onChange={event=>event.target.value==='p'?editor?.chain().focus().setParagraph().run():editor?.chain().focus().setHeading({level:event.target.value==='h2'?2:3}).run()}><option value="p">Paragraph</option><option value="h2">Heading 2</option><option value="h3">Heading 3</option></select><span className="editor-divider"/>{tool('Bold',Bold,()=>{editor?.chain().focus().toggleBold().run();},editor?.isActive('bold'))}{tool('Italic',Italic,()=>{editor?.chain().focus().toggleItalic().run();},editor?.isActive('italic'))}{tool('Underline',Underline,()=>{editor?.chain().focus().toggleUnderline().run();},editor?.isActive('underline'))}<span className="editor-divider"/>{tool('Bullet list',List,()=>{editor?.chain().focus().toggleBulletList().run();},editor?.isActive('bulletList'))}{tool('Numbered list',ListOrdered,()=>{editor?.chain().focus().toggleOrderedList().run();},editor?.isActive('orderedList'))}{tool('Quote',Quote,()=>{editor?.chain().focus().toggleBlockquote().run();},editor?.isActive('blockquote'))}{tool('Add link',LinkIcon,()=>{setUrl(editor?.getAttributes('link').href||'');setLinkError('');setLinkOpen(!linkOpen);},editor?.isActive('link'))}{tool('Remove link',Unlink,()=>{editor?.chain().focus().extendMarkRange('link').unsetLink().run();},false,!editor?.isActive('link'))}{tool('Clear formatting',RemoveFormatting,()=>{editor?.chain().focus().unsetAllMarks().clearNodes().run();})}<span className="editor-divider"/></>}{tool('Undo',Undo2,()=>{editor?.chain().focus().undo().run();},false,!editor?.can().undo())}{tool('Redo',Redo2,()=>{editor?.chain().focus().redo().run();},false,!editor?.can().redo())}{plain&&<span className="editor-mode">Plain text</span>}</div>
 {linkOpen&&!plain&&<div className="editor-link"><input type="text" aria-label={'Link URL in '+label} value={url} disabled={locked} placeholder="https://example.com" onChange={event=>{setUrl(event.target.value);setLinkError('');}} onKeyDown={event=>{if(event.key==='Enter')event.preventDefault();}}/><button type="button" disabled={locked} onClick={()=>{if(!/^(https?:\/\/|mailto:)/i.test(url.trim())){setLinkError('Use an https://, http:// or mailto: link.');return;}editor?.chain().focus().extendMarkRange('link').setLink({href:url.trim()}).run();setLinkOpen(false);}}>Apply</button><button type="button" onClick={()=>setLinkOpen(false)}>Cancel</button>{linkError&&<small role="alert">{linkError}</small>}</div>}
 <EditorContent editor={editor}/><div className="editor-footer"><span>{plain?'Line breaks and plain text are preserved.':'Use the toolbar to format your content.'}</span><span>{text.length.toLocaleString()} / {maxLength.toLocaleString()}</span></div>
 </div>;
}
export function RichContent({value,className=''}:{value:string;className?:string}){return <div className={'rich-content '+className} dangerouslySetInnerHTML={{__html:editorContent(value)}}/>}

