export type Product={id:string;name:string;slug:string;sku:string;type:string;price:number;sale_price?:number|null;stock:number;reserved:number;featured?:boolean;deal?:boolean;new_arrival?:boolean;sold_count?:number;review_count?:number;rating_average?:number|null;image?:string;gallery_images?:string[];brand_id?:string;category_ids:string[];description?:string;specifications?:string;warranty?:string;manual?:string;seo_title?:string;seo_description?:string;created_at:string;updated_at?:string};
export type HomepageSection={key:string;name:string;eyebrow?:string;heading:string;body?:string;image?:string;link?:string;link_label?:string;sort_order?:number};
export type Article={id:string;name:string;slug:string;category:string;excerpt:string;body:string;image:string;image_alt:string;minutes:number;sort_order?:number;created_at:string;updated_at?:string};
export type Coupon={id:string;name:string;code:string;description?:string;discount_kind:string;discount_type:string;value:number;minimum_type?:string;minimum_amount?:number;minimum_quantity?:number;starts_at?:string;ends_at?:string;once_per_customer?:boolean};
export type Catalog={products:Product[];brands:any[];categories:any[];coupons:Coupon[];banners:any[];homepage_sections:HomepageSection[];articles:Article[];pages:any[];delivery_zones:any[];locations:any;payment_methods:any[];settings:Record<string,string>;integration_warnings:string[]};
export const apiBase=()=>process.env.LARAVEL_API_URL||'http://127.0.0.1:8000';
let publicCatalog:{expires:number;promise:Promise<Catalog>}|undefined;
export async function catalog():Promise<Catalog>{if(publicCatalog&&publicCatalog.expires>Date.now())return publicCatalog.promise;const promise=(async()=>{const response=await fetch(`${apiBase()}/api/v1/store/catalog`,{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error('The store is temporarily unavailable. Please try again shortly.');const data=await response.json() as Catalog;if(data.integration_warnings?.length)console.error('Storefront CMS integration warnings:',data.integration_warnings);return data;})();publicCatalog={expires:Date.now()+15000,promise};try{return await promise;}catch(error){publicCatalog=undefined;console.error('Storefront catalog API failure:',error);throw error;}}
export async function brandHero(id:string):Promise<{image?:string|null;source?:string|null;author?:string|null;link?:string|null}>{try{const response=await fetch(`${apiBase()}/api/v1/store/brands/${id}/hero`,{cache:'no-store',signal:AbortSignal.timeout(20000)});if(!response.ok)return {};const data=await response.json();return data.hero||{};}catch{return {};}}
export const money=(value:number)=>'KES '+Number(value||0).toLocaleString('en-KE',{maximumFractionDigits:2});
export const price=(p:Product)=>p.sale_price??p.price;
export const slugify=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export async function storeRequest(path:string,method='GET',body?:any,key?:string){let response:Response;try{response=await fetch(`/api/store/${path}`,{method,headers:{'Content-Type':'application/json',...(key?{'Idempotency-Key':key}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});}catch{throw new Error('Unable to connect. Please try again.');}const data=await response.json().catch(()=>({message:'Unexpected response from the store.'}));if(!response.ok)throw new Error(Object.values(data.errors??{}).flat().join(' ')||data.message||'The request could not be completed.');return data;}

