"use client";
import AccountDashboard,{AccountSkeleton,AccountWishlist} from './account-dashboard';
import PasswordInput from './password-input';
import {useEffect,useState} from 'react';import Link from 'next/link';import {useSearchParams} from 'next/navigation';import {UserRound,ArrowRight,Package,Heart,MapPin} from 'lucide-react';import {storeRequest} from '@/lib/store';import {useStore} from './store';
export default function Account(){const {account,reloadAccount,notify}=useStore();const params=useSearchParams();const [mode,setMode]=useState('login'),[orders,setOrders]=useState<any[]>([]),[returns,setReturns]=useState<any[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[loading,setLoading]=useState(true);useEffect(()=>{reloadAccount().then((result:any)=>{if(result){setOrders(result.orders);setReturns(result.returns||[]);}setLoading(false);});},[]);
 if(loading)return <AccountSkeleton/>;
 if(!account&&params.get('tab')==='wishlist')return <main id="main" className="container account-page"><AccountWishlist/></main>;
 if(!account)return <main id="main" className="container auth-page"><div className="auth-story"><span className="eyebrow">GOOD TO HAVE YOU HERE</span><h1>A little more<br/>at home.</h1><p>Keep your favorites close, follow your orders and make your next visit a little easier.</p><div><Package size={23}/>Your orders, in one place</div><div><Heart size={23}/>A collection of your favorites</div><div><MapPin size={23}/>Addresses, ready for next time</div></div><form className="auth-form" onSubmit={async event=>{event.preventDefault();if(busy)return;const input=Object.fromEntries(new FormData(event.currentTarget));if(mode==='register'&&input.password!==input.password_confirmation){setMessage('Passwords do not match. Please confirm your password.');event.currentTarget.querySelector<HTMLInputElement>('[name="password_confirmation"]')?.focus();return;}setBusy(true);setMessage('');try{await storeRequest(mode,'POST',input);const result=await reloadAccount();setOrders(result?.orders??[]);setReturns(result?.returns??[]);notify(mode==='login'?'Welcome back.':'Your account is ready.');}catch(error:any){setMessage(error.message);}finally{setBusy(false);}}}><UserRound size={28}/><h2>{mode==='login'?'Welcome back.':'Make yourself at home.'}</h2><p>{mode==='login'?'Sign in to your LEEKAV account.':'Create an account for a better shopping experience.'}</p>{mode==='register'&&<label>Full name<input name="name" required maxLength={180} autoComplete="name"/></label>}<label>Email address<input name="email" type="email" required maxLength={180} autoComplete="email"/></label><label>Password<PasswordInput key={mode} label="Password" name="password" required minLength={mode==='register'?12:1} maxLength={72} autoComplete={mode==='login'?'current-password':'new-password'}/>{mode==='register'&&<small>Use at least 12 characters.</small>}</label>{mode==='register'&&<label>Confirm password<PasswordInput label="Confirm password" name="password_confirmation" required maxLength={72} autoComplete="new-password"/></label>}{message&&<p className="form-feedback error" role="alert">{message}</p>}<button className="button" disabled={busy}>{busy?'Please wait...':mode==='login'?'Sign in':'Create account'}<ArrowRight size={16}/></button><p>{mode==='login'?'New here?':'Already have an account?'} <button className="text-link" type="button" onClick={()=>{setMode(mode==='login'?'register':'login');setMessage('');}}>{mode==='login'?'Create an account':'Sign in'}</button></p><Link href="/contact" className="muted">Need help accessing your account?</Link></form></main>;
 return <AccountDashboard orders={orders} returns={returns}/>;}
