"use client";
import {useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowRight,ChevronLeft,ChevronRight,Clock3} from 'lucide-react';
import {blogPosts} from '@/lib/blog';
export default function BlogCarousel(){
 const track=useRef<HTMLDivElement>(null);const [position,setPosition]=useState({start:true,end:false});
 const update=()=>{const el=track.current;if(el)setPosition({start:el.scrollLeft<2,end:el.scrollLeft+el.clientWidth>=el.scrollWidth-2});};
 const move=(direction:number)=>{const el=track.current;if(!el)return;const card=el.firstElementChild as HTMLElement;el.scrollBy({left:direction*(card.offsetWidth+20),behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});};
 return <section className="container section home-blog" aria-labelledby="home-blog-title"><div className="section-heading"><div><span className="eyebrow">IDEAS FOR A BETTER EVERYDAY</span><h2 id="home-blog-title">The LEEKAV journal.</h2><p>Helpful guides and a little inspiration for your home.</p></div><div className="blog-carousel-controls"><button type="button" aria-label="Previous articles" disabled={position.start} onClick={()=>move(-1)}><ChevronLeft size={20}/></button><button type="button" aria-label="Next articles" disabled={position.end} onClick={()=>move(1)}><ChevronRight size={20}/></button></div></div><div ref={track} className="blog-carousel-track" onScroll={update} aria-label="Blog articles" tabIndex={0} onKeyDown={event=>{if(event.target===event.currentTarget&&['ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();move(event.key==='ArrowRight'?1:-1);}}}>{blogPosts.map(post=><article className="blog-card" key={post.slug}><Link href={'/blog/'+post.slug} className="blog-card-image" tabIndex={-1} aria-hidden="true"><img src={post.image} alt={post.alt} loading="lazy" width={640} height={400}/></Link><div className="blog-card-content"><div className="blog-card-meta"><span>{post.category}</span><span><Clock3 size={13}/>{post.minutes} min read</span></div><h3><Link href={'/blog/'+post.slug}>{post.title}</Link></h3><p>{post.excerpt}</p><Link className="blog-read-more" href={'/blog/'+post.slug}>Read article <ArrowRight size={15}/></Link></div></article>)}</div></section>;
}
