"use client";
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {ArrowRight,ChevronDown,Layers3,Leaf,Tag} from 'lucide-react';
import {Catalog,slugify} from '@/lib/store';
export default function MegaNavigation({data,mobileOpen,onNavigate}:{data:Catalog;mobileOpen:boolean;onNavigate:()=>void}){
 const [active,setActive]=useState<'categories'|'brands'|null>(null);const ref=useRef<HTMLElement>(null);const pathname=usePathname();const close=()=>{setActive(null);onNavigate();};
 useEffect(()=>{setActive(null);onNavigate();},[pathname]);
 useEffect(()=>{const outside=(event:PointerEvent)=>{if(!ref.current?.contains(event.target as Node))setActive(null);};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside);},[]);
 useEffect(()=>{if(!mobileOpen)setActive(null);},[mobileOpen]);
 const categories=data.categories;const roots=categories.filter(c=>!c.parent_id||!categories.some(parent=>parent.id===c.parent_id));
 const descendants=(id:string,seen:string[]=[],depth=0):React.ReactNode=>depth>5||seen.includes(id)?null:categories.filter(c=>c.parent_id===id).map(c=><li key={c.id}><Link href={'/categories/'+c.slug} onClick={close}>{c.name}</Link><ul>{descendants(c.id,[...seen,id],depth+1)}</ul></li>);
 return <nav ref={ref} aria-label="Main navigation" className={'container store-nav mega-nav '+(mobileOpen?'is-open':'')} onMouseLeave={()=>{if(window.matchMedia('(min-width:801px)').matches)setActive(null);}} onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node))setActive(null);}} onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();ref.current?.querySelector<HTMLButtonElement>('[aria-expanded="true"]')?.focus();setActive(null);}}}>
 <div className="mega-trigger-group">{(['categories','brands'] as const).map(kind=><button key={kind} type="button" className={'mega-trigger '+(active===kind?'selected':'')} aria-expanded={active===kind} aria-controls={'mega-'+kind} onClick={()=>setActive(window.matchMedia('(min-width:801px)').matches?kind:active===kind?null:kind)} onMouseEnter={()=>{if(window.matchMedia('(min-width:801px)').matches)setActive(kind);}}>{kind==='categories'?<Layers3 size={17}/>:<Tag size={17}/>}Shop by {kind==='categories'?'category':'brand'}<ChevronDown size={15}/></button>)}</div>
 <Link href="/products" onClick={close} onMouseEnter={()=>setActive(null)}>All products</Link><Link href="/products?sort=newest" onClick={close} onMouseEnter={()=>setActive(null)}>New arrivals</Link><Link href="/products?sale=1" className="nav-offer" onClick={close} onMouseEnter={()=>setActive(null)}>Special offers <ArrowRight size={14}/></Link>
 {active&&<div className="mega-panel" id={'mega-'+active}><div className="mega-content"><div className="mega-heading"><div><span className="eyebrow">FIND YOUR EVERYDAY UPGRADE</span><h2>{active==='categories'?'A good fit for every room.':'Great brands. Thoughtfully chosen.'}</h2></div><Link href="/products" onClick={close}>Explore all products <ArrowRight size={16}/></Link></div>
 {active==='categories'?<div className="mega-category-grid">{roots.map(category=><section className="mega-category" key={category.id}><Link className="mega-category-title" href={'/categories/'+category.slug} onClick={close}>{category.name}<ArrowRight size={14}/></Link><ul>{descendants(category.id)}</ul><Link className="mega-view-all" href={'/categories/'+category.slug} onClick={close}>View collection</Link></section>)}{!roots.length&&<p>Explore our latest products and find your perfect fit.</p>}</div>:<div className="mega-brand-grid">{data.brands.map(brand=><Link className="mega-brand-card" key={brand.id} href={'/brands/'+slugify(brand.name)} onClick={close}><span className={'brand-word '+slugify(brand.name)}>{brand.name}</span><span>{data.products.filter(p=>p.brand_id===brand.id).length} products to explore</span><strong>Shop collection <ArrowRight size={15}/></strong></Link>)}</div>}</div>
 <aside className="mega-feature"><span className="mega-feature-icon"><Leaf size={26}/></span><span className="eyebrow">MAKE YOURSELF AT HOME</span><h3>Little upgrades.<br/>Big everyday joy.</h3><p>Discover thoughtful finds from the brands you love.</p><Link href="/products?sale=1" onClick={close}>Discover special offers <ArrowRight size={16}/></Link></aside></div>}
 </nav>;
}

