"use client";
import MegaNavigation from './mega-navigation';
import React,{createContext,useContext,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {useRouter} from 'next/navigation';
import {Leaf,Search,ShoppingBag,UserRound,Heart,Menu,X,ArrowRight,Truck,ShieldCheck,Headphones,MessageCircle,Plus,Minus,Trash2,Check,Star,Tag} from 'lucide-react';
import {Catalog,Product,price,money,slugify,storeRequest} from '@/lib/store';
function Facebook({size=19,...props}:React.SVGProps<SVGSVGElement>&{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" {...props}><path d="M14 22v-9h3l.5-4H14V7c0-1.2.3-2 2-2h2V1.4C17.6 1.3 16.3 1 14.8 1 11.7 1 10 2.9 10 6.4V9H7v4h3v9z"/></svg>}
function Instagram({size=19,...props}:React.SVGProps<SVGSVGElement>&{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" {...props}><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg>}
type Line={id:string;quantity:number};
const Context=createContext<any>(null);
export const useStore=()=>useContext(Context);
export function StoreProvider({data,children}:{data:Catalog;children:React.ReactNode}){
 const [cart,setCart]=useState<Line[]>([]),[wishlist,setWishlist]=useState<string[]>([]),[account,setAccount]=useState<any>(null),[ready,setReady]=useState(false),[toast,setToast]=useState('');const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const notify=(message:string)=>{if(timer.current)clearTimeout(timer.current);setToast(message);timer.current=setTimeout(()=>setToast(''),4500);};
 const accountRequest=useRef(0);const reloadAccount=async()=>{const request=++accountRequest.current;try{const result=await storeRequest('account');if(request===accountRequest.current){setAccount(result.customer);setWishlist(result.customer.wishlist??[]);}return result;}catch{if(request===accountRequest.current)setAccount(null);return null;}};
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('olive-store-cart')||'[]');setCart(Array.isArray(saved)?saved.filter(line=>data.products.some(p=>p.id===line.id)&&Number.isInteger(line.quantity)&&line.quantity>0).map(line=>({...line,quantity:Math.min(line.quantity,100)})):[]);const favorites=JSON.parse(localStorage.getItem('olive-store-wishlist')||'[]');setWishlist(Array.isArray(favorites)?favorites:[]);}catch{}setReady(true);void reloadAccount();return()=>{if(timer.current)clearTimeout(timer.current);};},[]);
 useEffect(()=>{if(ready)localStorage.setItem('olive-store-cart',JSON.stringify(cart));},[cart,ready]);
 useEffect(()=>{if(ready)localStorage.setItem('olive-store-wishlist',JSON.stringify(wishlist));},[wishlist,ready]);
 const setQuantity=(id:string,quantity:number)=>{const product=data.products.find(p=>p.id===id);const max=product?Math.max(0,product.stock-(product.reserved||0)):0;setCart(lines=>quantity<=0||max<=0?lines.filter(line=>line.id!==id):lines.map(line=>line.id===id?{id,quantity:Math.min(quantity,max)}:line));};
 const add=(product:Product,quantity=1)=>{const available=product.stock-(product.reserved||0);const existing=cart.find(line=>line.id===product.id)?.quantity||0;if(product.type!=='Simple'||available<=0){notify('This product is currently unavailable.');return;}if(existing+quantity>available){notify('There are not enough units available.');return;}setCart(lines=>existing?lines.map(line=>line.id===product.id?{...line,quantity:line.quantity+quantity}:line):[...lines,{id:product.id,quantity}]);notify('Added to your bag.');};
 const favorite=async(id:string)=>{const next=wishlist.includes(id)?wishlist.filter(value=>value!==id):[...wishlist,id];setWishlist(next);if(account){try{await storeRequest('profile','PATCH',{name:account.name,phone:account.phone,wishlist:next});}catch(error:any){notify(error.message);}}};
 return <Context.Provider value={{data,cart,setCart,setQuantity,add,wishlist,favorite,account,reloadAccount,notify}}>{children}{toast&&<div className="store-toast" role="status"><Check size={18}/>{toast}<button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={17}/></button></div>}</Context.Provider>;
}
export function Header(){const {data,cart,wishlist,account}=useStore();const [search,setSearch]=useState(''),[open,setOpen]=useState(false),[suggestionsOpen,setSuggestionsOpen]=useState(false);const searchRef=useRef<HTMLFormElement>(null);const router=useRouter();const suggestions=search.trim()?data.products.filter((p:Product)=>p.name.toLowerCase().includes(search.toLowerCase())||p.sku.toLowerCase().includes(search.toLowerCase())).slice(0,5):[];
 useEffect(()=>{const outside=(event:PointerEvent)=>{if(!searchRef.current?.contains(event.target as Node)){setSuggestionsOpen(false);setSearch('');}};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside);},[]);
 return <><div className="announcement announcement-marquee" aria-label="Thoughtfully chosen. Delivered to your door. Delivery across selected Kenyan counties."><div className="announcement-track">{[0,1].map(copy=><div className="announcement-group" key={copy} aria-hidden={copy===1?true:undefined}>{[0,1].map(item=><span className="announcement-pair" key={item} aria-hidden={item===1?true:undefined}><span>Thoughtfully chosen. Delivered to your door.</span><span className="announcement-divider" aria-hidden="true">✦</span><span><Truck size={13}/>Delivery across selected Kenyan counties</span><span className="announcement-divider" aria-hidden="true">✦</span></span>)}</div>)}</div></div><header className="store-header"><div className="container header-main"><Link href="/" className="store-logo leekav-logo" aria-label="LEEKAV home"><img src="/brand/leekav-logo.png" alt="LEEKAV" width={2020} height={778}/></Link><form ref={searchRef} className="store-search" onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node))setSuggestionsOpen(false);}} onSubmit={event=>{event.preventDefault();router.push('/products?q='+encodeURIComponent(search));setSearch('');}}><Search size={19}/><input aria-label="Search products" placeholder="What can we help you find?" value={search} onChange={event=>{setSearch(event.target.value);setSuggestionsOpen(true);}} onFocus={()=>setSuggestionsOpen(true)} onKeyDown={event=>{if(event.key==='Escape'){setSearch('');setSuggestionsOpen(false);}}}/><button type="submit" aria-label="Submit search"><ArrowRight size={18}/></button>{suggestionsOpen&&search.trim()&&<div className="search-suggestions">{suggestions.length?suggestions.map((p:Product)=><Link href={'/products/'+p.slug} key={p.id} onClick={()=>setSearch('')}><span>{p.name}</span><strong>{money(price(p))}</strong></Link>):<p>No products found. Try another search.</p>}</div>}</form><div className="header-tools"><Link href="/account" className={account?"header-account signed-in":"header-account"} aria-label={account?"My account: "+account.name:"My account"} title={account?.name||"My account"}><UserRound size={22}/><small>{account?.name||"Account"}</small></Link><Link href="/account?tab=wishlist" aria-label="Wishlist"><Heart size={22}/>{wishlist.length>0&&<b>{wishlist.length}</b>}</Link><Link href="/cart" aria-label="Shopping bag"><ShoppingBag size={22}/>{cart.length>0&&<b>{cart.reduce((sum:number,line:Line)=>sum+line.quantity,0)}</b>}</Link><button className="mobile-menu" aria-label="Toggle navigation" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div><MegaNavigation data={data} mobileOpen={open} onNavigate={()=>setOpen(false)}/></header></>;
}
export function ProductImage({product,priority=false,className=''}:{product:Product;priority?:boolean;className?:string}){return product.image?<Image src={product.image} alt={product.name} width={640} height={640} className={'product-image '+className} priority={priority} unoptimized={product.image.endsWith('.svg')}/>:<div className="image-placeholder"><ShoppingBag size={50}/><span>{product.name}</span></div>}
export function ProductCard({product}:{product:Product}){const {data,add,wishlist,favorite}=useStore();const brand=data.brands.find((b:any)=>b.id===product.brand_id);const discount=product.sale_price!=null&&product.sale_price<product.price?Math.round((1-product.sale_price/product.price)*100):0;const available=product.type==='Simple'&&product.stock-(product.reserved||0)>0;
 return <article className="product-card"><div className="product-card-image"><Link href={'/products/'+product.slug}><ProductImage product={product}/></Link>{discount>0&&<span className="offer-badge"><Tag size={12} aria-hidden="true"/>Save {discount}%</span>}<button className={'favorite-button '+(wishlist.includes(product.id)?'selected':'')} aria-label={(wishlist.includes(product.id)?'Remove from':'Add to')+' wishlist: '+product.name} onClick={()=>favorite(product.id)}><Heart size={18} fill={wishlist.includes(product.id)?'currentColor':'none'}/></button></div><div className="product-card-info"><small className="product-brand">{brand?.name||'LEEKAV COLLECTION'}</small><Link href={'/products/'+product.slug}><h3>{product.name}</h3></Link><div className="product-price"><strong>{money(price(product))}</strong>{discount>0&&<del>{money(product.price)}</del>}</div><div className="product-card-bottom"><span className={available?'in-stock':'out-stock'}><i/>{available?'In stock':'Out of stock'}</span><button className="add-button" disabled={!available} aria-label={'Add '+product.name+' to bag'} onClick={()=>add(product)}><Plus size={16}/>Add</button></div></div></article>;
}
export function Newsletter(){const [busy,setBusy]=useState(false),[message,setMessage]=useState('');return <section className="newsletter container"><div><span className="eyebrow">A LITTLE INSPIRATION, IN YOUR INBOX</span><h2>Make yourself at home.</h2><p>New arrivals, thoughtful finds and offers worth opening.</p></div><form onSubmit={async event=>{event.preventDefault();if(busy)return;setBusy(true);setMessage('');const form=event.currentTarget;try{const result=await storeRequest('newsletter','POST',{email:new FormData(form).get('email')});setMessage(result.message);form.reset();}catch(error:any){setMessage(error.message);}finally{setBusy(false);}}}><div><input name="email" type="email" required maxLength={180} aria-label="Newsletter email" placeholder="Your email address"/><button disabled={busy} aria-label="Subscribe">{busy?'...':<ArrowRight size={21}/>}</button></div><small role="status">{message||'By subscribing, you agree to receive our newsletters. You can ask us to unsubscribe at any time.'}</small></form></section>}
export function Footer(){const {data}=useStore();const settings=data.settings;const whatsapp=(settings.whatsapp||settings.phone||'').replace(/[^0-9]/g,'');return <><Newsletter/><footer className="store-footer"><div className="container footer-grid"><div><Link href="/" className="footer-logo leekav-logo" aria-label="LEEKAV home"><img src="/brand/leekav-logo.png" alt="LEEKAV" width={2020} height={778}/></Link><p>Good brands. Thoughtful choices.<br/>A little better, every day.</p><span className="footer-location">Kenya / KES</span><div className="footer-socials" aria-label="Follow LEEKAV">{[{name:'Facebook',url:settings.facebook,Icon:Facebook},{name:'Instagram',url:settings.instagram,Icon:Instagram},{name:'WhatsApp',url:whatsapp?'https://wa.me/'+whatsapp:'',Icon:MessageCircle}].map(({name,url,Icon})=>/^https?:\/\//.test(url||'')?<a key={name} href={url} target="_blank" rel="noopener noreferrer" aria-label={name} title={name}><Icon size={19} aria-hidden="true"/></a>:<span key={name} className="social-unavailable" role="img" aria-label={name} title={name}><Icon size={19} aria-hidden="true"/></span>)}</div></div><div><h3>Explore</h3><Link href="/products">All products</Link>{data.brands.map((b:any)=><Link key={b.id} href={'/brands/'+slugify(b.name)}>{b.name}</Link>)}<Link href="/products?sale=1">Special offers</Link></div><div><h3>Here to help</h3>{[['About us','about'],['Contact us','contact'],['Frequently asked questions','faq'],['Shipping & returns','shipping-returns'],['My account','account']].map(([label,path])=><Link key={path} href={'/'+path}>{label}</Link>)}</div><div><h3>Get in touch</h3>{settings.phone&&<a href={'tel:'+settings.phone}>{settings.phone}</a>}{settings.email&&<a href={'mailto:'+settings.email}>{settings.email}</a>}<p>{settings.address||'Kenya'}</p>{whatsapp&&<a href={'https://wa.me/'+whatsapp} target="_blank" rel="noreferrer">Chat on WhatsApp <ArrowRight size={13}/></a>}</div></div><div className="container footer-bottom"><span>Copyright {new Date().getFullYear()} LEEKAV. All rights reserved.</span><div><Link href="/privacy">Privacy policy</Link><Link href="/terms-conditions">Terms & conditions</Link></div><span>Built around everyday living.</span></div></footer>{whatsapp&&<a className="whatsapp-float" href={'https://wa.me/'+whatsapp} aria-label="Chat on WhatsApp" target="_blank" rel="noreferrer"><MessageCircle size={24}/></a>}</>}
export function Benefits(){return <section className="benefits container">{[[Truck,'Delivery, made simple','Rates tailored to your county'],[ShieldCheck,'Brands you know','Products from trusted names'],[Headphones,'A helping hand','Real people, ready to help']].map(([Icon,title,text]:any)=><div key={title}><Icon size={27} strokeWidth={1.4}/><span><strong>{title}</strong><small>{text}</small></span></div>)}</section>}

