import BlogCarousel from '@/components/blog-carousel';
import Hero from '@/components/hero';
import HomeEditorial from '@/components/home-editorial';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight} from 'lucide-react';
import {catalog,slugify} from '@/lib/store';
import {menuCategories,productsHref} from '@/lib/mega-menu';
import {ProductCard,Benefits} from '@/components/store';
const curatedCategories=menuCategories.map(category=>[category.name,category.image,productsHref({q:category.query})]);
export default async function Home(){const data=await catalog();const promotion=data.banners.find(b=>b.placement==='Promotional banner');return <main id="main"><Hero data={data}/><Benefits/><section className="container section home-categories"><div className="section-heading"><div><span className="eyebrow">SHOP BY CATEGORY</span><h2>Find what fits your home.</h2></div><Link href="/products">Explore all categories <ArrowUpRight size={17}/></Link></div><div className="category-image-grid">{curatedCategories.map(([name,image,href])=><Link className="category-image-card" href={href} key={name}><span className="category-image"><img src={image} alt={`${name} products`} loading="lazy"/></span><strong>{name}</strong><small>Shop collection <ArrowUpRight size={14}/></small></Link>)}</div></section><section className="container section"><div className="section-heading"><div><span className="eyebrow">A FEW EVERYDAY FAVORITES</span><h2>Good choices. Great brands.</h2></div><Link href="/products">Shop all products <ArrowUpRight size={17}/></Link></div><div className="product-grid home-product-grid">{[...data.products].sort((a,b)=>Number(Boolean(b.image))-Number(Boolean(a.image))).slice(0,4).map(p=><ProductCard key={p.id} product={p}/>)}</div></section><HomeEditorial headline={promotion?.headline} link={promotion?.link} image={promotion?.image||undefined} imageAlt={promotion?.headline||promotion?.name}/><section className="container section"><div className="section-heading"><div><span className="eyebrow">YOUR NEXT GREAT FIND</span><h2>Fresh additions to your home.</h2></div><Link href="/products?sort=newest">See what's new <ArrowUpRight size={17}/></Link></div><div className="product-grid home-product-grid">{[...data.products].sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,4).map(p=><ProductCard key={p.id} product={p}/>)}</div></section><BrandsMarquee brands={data.brands}/><BlogCarousel/></main>}
function BrandsMarquee({brands}:{brands:any[]}){const fallback:{[key:string]:string}={lg:'/assets/brands/lg.png',midea:'/assets/brands/midea.png',karcher:'/assets/brands/karcher.png'};const visible=brands.map(brand=>({...brand,image:brand.image||fallback[slugify(brand.name)]})).filter(brand=>brand.image);if(!visible.length)return null;return <section className="container section brand-marquee-section" aria-labelledby="home-brands-title"><div className="brand-section-heading"><span className="eyebrow">OUR BRANDS</span><h2 id="home-brands-title">Brands you know and trust</h2><p>Genuine products from leading names, backed by warranty and local support.</p></div><div className="brand-marquee" aria-label="Brand logos"><div className="brand-marquee-track">{visible.map(brand=><Link className="brand-marquee-item" href={'/brands/'+slugify(brand.name)} key={brand.id} aria-label={`Shop ${brand.name}`}><img src={brand.image} alt={brand.name} loading="lazy"/></Link>)}</div></div></section>}
