import {filter} from '@/lib/filter';
import HomepageReveal from '@/components/homepage-reveal';
import ProductCarousel from '@/components/product-carousel';
import HomeDeals from '@/components/home-deals';
import BrandMarquee from '@/components/brand-marquee';
import BlogCarousel from '@/components/blog-carousel';
import Hero from '@/components/hero';
import HomeEditorial from '@/components/home-editorial';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight} from 'lucide-react';
import {catalog,slugify} from '@/lib/store';
import {menuCategories,menuCategoryHref} from '@/lib/mega-menu';
import {ProductCard,Benefits} from '@/components/store';
export default async function Home(){const data=await catalog();const arrivals=filter(data.products,{sort:'newest'}).slice(0,4);const arrivalIds=new Set(arrivals.map(product=>product.id));const offers=filter(data.products,{hot:'0'}).filter(product=>!arrivalIds.has(product.id)).sort((a,b)=>Number(Boolean(b.image))-Number(Boolean(a.image))).slice(0,4);const usedIds=new Set([...arrivals,...offers].map(product=>product.id));const deals=data.products.filter(product=>!usedIds.has(product.id));const curatedCategories=menuCategories.map(category=>[category.id==='small-appliances'?'Small Appliances':category.name,category.image,menuCategoryHref(category,data)]);const promotion=data.banners.find(b=>b.placement==='Promotional banner');return <main id="main"><HomepageReveal/><Hero data={data}/><Benefits/><section className="container section home-categories"><div className="section-heading"><div><span className="eyebrow">SHOP BY CATEGORY</span><h2>Find what fits your home.</h2></div><Link href="/products">Explore all categories <ArrowUpRight size={17}/></Link></div><div className="category-image-grid">{curatedCategories.map(([name,image,href])=><Link className="category-image-card" href={href} key={name}><span className="category-image"><img src={image} alt={`${name} products`} loading="lazy"/></span><strong>{name}</strong><small>Shop collection <ArrowUpRight size={14}/></small></Link>)}</div></section><section className="container section" data-home-collection="featured"><div className="section-heading"><div><span className="eyebrow">A FEW EVERYDAY FAVORITES</span><h2>Good choices. Great brands.</h2></div><Link href="/products?offer=1">Shop all products <ArrowUpRight size={17}/></Link></div><ProductCarousel products={offers} label="everyday offers"/></section><HomeDeals products={deals} tagline={data.settings.deals_tagline}/><HomeEditorial headline={promotion?.headline} link={promotion?.link} image="/assets/banners/modern-smart-home-panorama.webp" imageAlt="Modern living room with a television, refrigerator, washing machine and robot vacuum"/><section className="container section" data-home-collection="arrivals"><div className="section-heading"><div><span className="eyebrow">YOUR NEXT GREAT FIND</span><h2>Fresh additions to your home.</h2></div><Link href="/products?sort=newest">See what's new <ArrowUpRight size={17}/></Link></div><ProductCarousel products={arrivals} label="new arrivals"/></section><BrandsMarquee brands={data.brands}/><BlogCarousel/></main>}
function BrandsMarquee({brands}:{brands:any[]}){const fallback:{[key:string]:string}={lg:'/assets/brands/lg.png',midea:'/assets/brands/midea.png',karcher:'/assets/brands/karcher.png'};const visible=brands.map(brand=>({...brand,image:brand.image||fallback[slugify(brand.name)]})).filter(brand=>brand.image);if(!visible.length)return null;return <section className="container section brand-marquee-section" aria-labelledby="home-brands-title"><div className="brand-section-heading"><span className="eyebrow">OUR BRANDS</span><h2 id="home-brands-title">Brands you know and trust</h2><p>Genuine products from leading names, backed by warranty and local support.</p></div><div className="brand-marquee" aria-label="Brand logos"><BrandMarquee brands={visible}/></div></section>}
