import {notFound} from 'next/navigation';
import {headers} from 'next/headers';
import {catalog,slugify} from '@/lib/store';
import CategoryListing from '@/components/category-listing';
import CollectionBanner from '@/components/collection-banner';
import BrandContent from '@/components/brand-content';
import {ShieldCheck,PackageCheck,Truck,Headphones} from 'lucide-react';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const data=await catalog();const {slug}=await params;const brand=data.brands.find(b=>slugify(b.name)===slug);return {title:brand?.seo_title||brand?.name||'Brand',description:brand?.seo_description||brand?.description||undefined}}
export default async function Brand({params}:{params:Promise<{slug:string}>}){
 const data=await catalog();const {slug}=await params;const brand=data.brands.find(b=>slugify(b.name)===slug);if(!brand)notFound();const products=data.products.filter(p=>p.brand_id===brand.id);const bannerImage=brand.banner;const h=await headers();const origin=process.env.NEXT_PUBLIC_SITE_URL||`${h.get('x-forwarded-proto')||'http'}://${h.get('host')||'localhost:3000'}`;
 const structured=[{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[['Home','/'],['Brands','/products'],[brand.name,'/brands/'+slug]].map(([name,path],i)=>({'@type':'ListItem',position:i+1,name,item:new URL(path,origin).href}))},{'@context':'https://schema.org','@type':'Brand',name:brand.name,description:brand.description||undefined,logo:brand.image?new URL(brand.image,origin).href:undefined,url:new URL('/brands/'+slug,origin).href}];
 return <div className="premium-brand"><CollectionBanner brand name={brand.name} description={brand.description} image={bannerImage||undefined} count={products.length}/><section className="container brand-trust"><h2>Why buy {brand.name} at LEEKAV</h2><div>{[[ShieldCheck,'Official warranty','Review coverage on each product'],[PackageCheck,'Genuine products',`Explore real ${brand.name} models`],[Truck,'Delivery','Confirm your county at checkout'],[Headphones,'Local support','Our team can help you choose']].map(([Icon,label,detail]:any)=><div key={label}><Icon size={22}/><span><strong>{label}</strong><small>{detail}</small></span></div>)}</div></section><p className="container brand-delivery"><Truck size={16} aria-hidden="true"/>Delivery options and charges are confirmed for your county at checkout.</p><CategoryListing data={data} category={{id:brand.id,name:brand.name}} products={products} brandName={brand.name}/><BrandContent brand={brand} brands={data.brands} image={bannerImage||undefined}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replaceAll('<',String.fromCharCode(92)+'u003c')}}/></div>
}
